// Autogenerated placeholder data for the "past itineraries" + multiplayer demo.
// These are static examples (not in the database) so we can show shared trips and
// visit collaborators' profiles without a real social graph yet.

export type Member = {
  id: string;
  name: string;
  handle: string;
  initials: string;
  color: string;
  neighborhood: string;
  bio: string;
  following: number;
  followers: number;
};

export type PastStop = { name: string; time: string; walk: string };

export type PastItinerary = {
  id: string;
  name: string;
  date: string;
  members: string[]; // member ids
  stops: PastStop[];
};

export const MEMBERS: Record<string, Member> = {
  maya: {
    id: 'maya',
    name: 'Maya Kim',
    handle: 'maya_k',
    initials: 'MK',
    color: '#e0556b',
    neighborhood: 'West Village',
    bio: 'Cocktail enthusiast & dumpling hunter. DM me your speakeasy finds.',
    following: 284,
    followers: 1203,
  },
  jess: {
    id: 'jess',
    name: 'Jess Nguyen',
    handle: 'jess_nyc',
    initials: 'JN',
    color: '#5b6cf0',
    neighborhood: 'Williamsburg',
    bio: 'Always chasing the next rooftop sunset. 🌇',
    following: 512,
    followers: 884,
  },
  tony: {
    id: 'tony',
    name: 'Tony Diaz',
    handle: 'tonyd',
    initials: 'TD',
    color: '#f59e0b',
    neighborhood: 'Lower East Side',
    bio: 'Jazz, ramen, repeat.',
    following: 173,
    followers: 642,
  },
  kira: {
    id: 'kira',
    name: 'Kira Lee',
    handle: 'kira_l',
    initials: 'KL',
    color: '#14b8a6',
    neighborhood: 'Bushwick',
    bio: 'Vintage shops & natural wine. Will walk far for both.',
    following: 391,
    followers: 1567,
  },
  raf: {
    id: 'raf',
    name: 'Raf Santos',
    handle: 'raf',
    initials: 'RS',
    color: '#8b5cf6',
    neighborhood: 'Astoria',
    bio: 'Souvlaki scout. Bread is a love language.',
    following: 220,
    followers: 305,
  },
  sam: {
    id: 'sam',
    name: 'Sam Tran',
    handle: 'sam_t',
    initials: 'ST',
    color: '#ec4899',
    neighborhood: 'Park Slope',
    bio: 'Museum member, park picnicker, matcha completionist.',
    following: 147,
    followers: 498,
  },
  alex: {
    id: 'alex',
    name: 'Alex Rivera',
    handle: 'alex_l',
    initials: 'AL',
    color: '#0ea5e9',
    neighborhood: 'Greenpoint',
    bio: 'Coffee crawls and live shows. Catch me at a basement gig.',
    following: 633,
    followers: 2104,
  },
};

export const PAST_ITINERARIES: PastItinerary[] = [
  {
    id: 'pi-1',
    name: 'Brooklyn Bar Crawl',
    date: 'May 24',
    members: ['raf', 'tony', 'kira'],
    stops: [
      { name: 'Maison Premiere', time: '6:30pm', walk: 'Start here' },
      { name: 'Clover Club', time: '7:45pm', walk: '8 min walk' },
      { name: 'Leyenda', time: '9:00pm', walk: '6 min walk' },
      { name: 'Sunken Harbor Club', time: '10:30pm', walk: '12 min walk' },
      { name: 'Black Flamingo', time: '12:00am', walk: '9 min walk' },
    ],
  },
  {
    id: 'pi-2',
    name: 'West Village Date Night',
    date: 'May 10',
    members: ['maya', 'jess'],
    stops: [
      { name: 'I Sodi', time: '7:00pm', walk: 'Start here' },
      { name: 'Little Branch', time: '8:30pm', walk: '4 min walk' },
      { name: 'Levain Bakery', time: '10:00pm', walk: '7 min walk' },
    ],
  },
  {
    id: 'pi-3',
    name: 'Museum Mile Sunday',
    date: 'Apr 28',
    members: ['sam', 'kira', 'maya', 'alex'],
    stops: [
      { name: 'The Met', time: '10:00am', walk: 'Start here' },
      { name: 'Guggenheim', time: '12:30pm', walk: '10 min walk' },
      { name: 'Neue Galerie', time: '2:00pm', walk: '5 min walk' },
      { name: 'Café Sabarsky', time: '3:30pm', walk: '1 min walk' },
    ],
  },
];
