// Autogenerated demo comments per spot — to show how people leave live notes.
// Deterministic per spot name so they stay consistent; category-relevant text.
import { MEMBERS } from './demoTrips';

export type DemoComment = {
  id: string;
  handle: string;
  initials: string;
  ago: string;
  text: string;
  base: number; // starting "still accurate" count
};

const POOLS: Record<string, string[]> = {
  food: [
    'The line is so long right now.',
    'Got a table for two right away.',
    'Kitchen is fast tonight — food in 10 min.',
    'Packed but 100% worth the wait.',
    'Happy hour just started, deals on now.',
    'Walk-in friendly at the moment.',
  ],
  nightlife: [
    'No cover tonight.',
    'Cocktails are incredible but pricey. Worth it for the vibe.',
    'DJ just started and the crowd is electric.',
    'Line outside moved fast, we got in within 10.',
    'Rooftop has open seats right now.',
    'Pretty chill — easy to grab a spot at the bar.',
  ],
  museum: [
    'Tickets are discounted today.',
    'Super quiet right now, no crowds.',
    'New exhibit just opened — go see it.',
    'Pay-what-you-wish this evening.',
    'Coat check line is short.',
  ],
  park: [
    'Perfect weather — grab a spot on the lawn.',
    'Food trucks are out today.',
    'Pretty empty right now.',
    'Live music in the park tonight.',
    'Golden hour here is unreal.',
  ],
  landmark: [
    'Crowded but the views are unreal.',
    'Short lines right now.',
    'Best photo spot is on the north side.',
    'Packed — maybe come back later.',
    'Moving fast through security.',
  ],
  shopping: [
    'Big sale happening right now.',
    'Surprisingly empty — easy browsing.',
    'New drop just hit the shelves.',
    'Fitting rooms have no wait.',
  ],
  transit: [
    'Trains running on time.',
    'Pretty crowded on the platform.',
    'Minor delays right now.',
    'Restrooms are open and clean-ish.',
  ],
  venue: [
    'Doors just opened.',
    'Crowd is hyped tonight.',
    'Still seats available.',
    'Merch line is short right now.',
  ],
  default: [
    'Really chill right now.',
    'Busier than usual.',
    'Great vibe at the moment.',
  ],
};

const TIMES = ['4m ago', '12m ago', '28m ago', '1h ago', '2h ago', '40m ago'];
const AUTHORS = ['maya', 'jess', 'tony', 'kira', 'raf', 'sam', 'alex'];

function hash(s: string): number {
  let h = 0;
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0;
  return Math.abs(h);
}

export function demoCommentsFor(name: string, category: string): DemoComment[] {
  const pool = POOLS[category.toLowerCase()] ?? POOLS.default;
  const h = hash(name);
  const count = 2 + (h % 2); // 2 or 3 comments
  const used = new Set<number>();
  const out: DemoComment[] = [];
  for (let i = 0; i < count; i++) {
    const pi = (h + i * 5) % pool.length;
    if (used.has(pi)) continue;
    used.add(pi);
    const a = MEMBERS[AUTHORS[(h + i * 3) % AUTHORS.length]];
    out.push({
      id: `${name}#${i}`,
      handle: a.handle,
      initials: a.initials,
      ago: TIMES[(h + i) % TIMES.length],
      text: pool[pi],
      base: (h + i * 7) % 6,
    });
  }
  return out;
}
