// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AddPhotoReducer from "../add_photo_reducer";
import AddToTripReducer from "../add_to_trip_reducer";
import AddToWishlistReducer from "../add_to_wishlist_reducer";
import ConfirmReportReducer from "../confirm_report_reducer";
import CreateWishlistReducer from "../create_wishlist_reducer";
import RemoveTripStopReducer from "../remove_trip_stop_reducer";
import RemoveWishlistItemReducer from "../remove_wishlist_item_reducer";
import ReorderTripStopsReducer from "../reorder_trip_stops_reducer";
import ReportWaitReducer from "../report_wait_reducer";
import SetHandleReducer from "../set_handle_reducer";
import SetProfileReducer from "../set_profile_reducer";
import SetSavedPublicReducer from "../set_saved_public_reducer";
import SubmitReportReducer from "../submit_report_reducer";
import ToggleSavedReducer from "../toggle_saved_reducer";

export type AddPhotoParams = __Infer<typeof AddPhotoReducer>;
export type AddToTripParams = __Infer<typeof AddToTripReducer>;
export type AddToWishlistParams = __Infer<typeof AddToWishlistReducer>;
export type ConfirmReportParams = __Infer<typeof ConfirmReportReducer>;
export type CreateWishlistParams = __Infer<typeof CreateWishlistReducer>;
export type RemoveTripStopParams = __Infer<typeof RemoveTripStopReducer>;
export type RemoveWishlistItemParams = __Infer<typeof RemoveWishlistItemReducer>;
export type ReorderTripStopsParams = __Infer<typeof ReorderTripStopsReducer>;
export type ReportWaitParams = __Infer<typeof ReportWaitReducer>;
export type SetHandleParams = __Infer<typeof SetHandleReducer>;
export type SetProfileParams = __Infer<typeof SetProfileReducer>;
export type SetSavedPublicParams = __Infer<typeof SetSavedPublicReducer>;
export type SubmitReportParams = __Infer<typeof SubmitReportReducer>;
export type ToggleSavedParams = __Infer<typeof ToggleSavedReducer>;

