// Curated details for our NYC spots (no API key needed). Generated from the
// spreadsheet — see scripts/genspots.mjs.
export type PlaceInfo = {
  blurb?: string;
  website?: string;
  price?: string;
  tags?: string[];
  rating?: number;
  ratingCount?: number;
  hours?: string;
  address?: string;
  phone?: string;
};

export const PLACE_INFO: Record<string, PlaceInfo> = {
  'Macy\'s Herald Square': {
    blurb: 'Flagship department store — 11 floors of everything, since 1902.',
    website: 'https://www.macys.com/stores/ny/new-york/herald-square_2.html',
    tags: ['Shopping', 'Landmark', 'Restrooms'],
    hours: 'Mon–Sat 10am–9pm, Sun 11am–8pm',
    address: '151 W 34th St, New York, NY 10001',
    phone: '+1 212-695-4400',
    rating: 4.3,
    ratingCount: 18211,
  },
  'Empire State Building': {
    blurb: 'Art-deco icon with 86th & 102nd floor observation decks.',
    website: 'https://www.esbnyc.com',
    tags: ['Landmark', 'Observatory', 'Tickets'],
    hours: 'Daily 8am–2am',
    address: '20 W 34th St, New York, NY 10118',
    phone: '+1 212-736-3100',
    rating: 4.7,
    ratingCount: 98342,
  },
  'Koreatown (32nd St)': {
    blurb: 'Neon "K-Town" — Korean BBQ, karaoke and 24-hour eats.',
    website: 'https://www.explorektownnyc.com',
    tags: ['Neighborhood', 'Food', 'Nightlife'],
    hours: '24/7 (varies by venue)',
    address: 'W 32nd St, New York, NY 10001',
    phone: '+1 212-290-2460',
  },
  'Madison Square Garden': {
    blurb: 'The Garden — Knicks, Rangers and arena shows above Penn.',
    website: 'https://www.msg.com/madison-square-garden',
    tags: ['Arena', 'Entertainment', 'Sports'],
    hours: 'Event days only (varies)',
    address: '4 Pennsylvania Plaza, New York, NY 10001',
    phone: '+1 212-465-6741',
  },
  'Penn Station': {
    blurb: 'Busiest transit hub in the hemisphere — LIRR, NJ Transit, Amtrak.',
    website: 'https://www.amtrak.com/stations/nyp',
    tags: ['Transit', 'Trains', 'Restrooms'],
    hours: '24/7',
    address: '8th Ave & W 31st St, New York, NY 10001',
    phone: '+1 212-630-6400',
  },
  'Bryant Park': {
    blurb: 'Midtown lawn behind the library — seasonal market & ice rink.',
    website: 'https://bryantpark.org',
    tags: ['Park', 'Free Wi-Fi', 'Events'],
    hours: 'Daily 7am–10pm (seasonal)',
    address: '41st to 42nd St, 5th to 6th Ave, New York, NY 10018',
    phone: '+1 212-768-4242',
    rating: 4.7,
    ratingCount: 45120,
  },
  'NY Public Library': {
    blurb: 'The Stephen A. Schwarzman Building and its Rose Reading Room.',
    website: 'https://www.nypl.org',
    tags: ['Library', 'Landmark', 'Free'],
    hours: 'Mon–Thu 10am–8pm, Fri–Sat 10am–6pm, Sun 1pm–5pm',
    address: '476 5th Ave, New York, NY 10018',
    phone: '+1 917-275-6975',
    rating: 4.8,
    ratingCount: 27640,
  },
  'Times Square': {
    blurb: 'The Crossroads of the World — billboards, theaters, crowds.',
    website: 'https://www.timessquarenyc.org',
    tags: ['Landmark', 'Entertainment', 'Open 24h'],
    hours: '24/7',
    address: 'Broadway & 7th Ave, New York, NY 10036',
    phone: '+1 212-768-1560',
    rating: 4.7,
    ratingCount: 212003,
  },
  'Madison Square Park': {
    blurb: 'Leafy Flatiron square and the original Shake Shack.',
    website: 'https://madisonsquarepark.org',
    tags: ['Park', 'Dog run', 'Art'],
    hours: 'Daily 6am–11pm',
    address: '11 Madison Ave, New York, NY 10010',
    phone: '+1 212-538-3860',
  },
  'Eataly NYC Flatiron': {
    blurb: 'Sprawling Italian market, counters and rooftop beer garden.',
    website: 'https://www.eataly.com/us_en/stores/nyc-flatiron',
    tags: ['Italian', 'Market', 'Rooftop'],
    hours: 'Daily 9am–11pm',
    address: '200 5th Ave, New York, NY 10010',
    phone: '+1 212-229-2560',
    rating: 4.5,
    ratingCount: 12044,
  },
  'Flatiron Building': {
    blurb: '1902 Beaux-Arts wedge where Broadway meets Fifth.',
    website: 'https://www.flatirondistrict.nyc',
    tags: ['Landmark', 'Photo spot'],
    hours: 'Exterior 24/7',
    address: '175 5th Ave, New York, NY 10010',
    phone: '+1 212-826-2980',
    rating: 4.6,
    ratingCount: 9032,
  },
  'Shake Shack (Madison Sq)': {
    blurb: 'The original Shake Shack kiosk in Madison Square Park.',
    website: 'https://www.shakeshack.com',
    tags: ['Burgers', 'Outdoor seating'],
    hours: 'Daily 11am–11pm',
    address: 'Madison Ave & E 23rd St, New York, NY 10010',
    phone: '+1 212-889-6600',
    rating: 4.5,
    ratingCount: 6210,
  },
  'The Morgan Library': {
    blurb: 'J.P. Morgan\'s library turned museum of manuscripts & art.',
    website: 'https://www.themorgan.org',
    tags: ['Museum', 'Café'],
    hours: 'Tue–Thu 10:30am–5pm, Fri 10:30am–9pm, Sat 10am–6pm, Sun 11am–6pm',
    address: '225 Madison Ave, New York, NY 10016',
    phone: '+1 212-685-0008',
    rating: 4.7,
    ratingCount: 3890,
  },
  'Greeley Square': {
    blurb: 'Pocket park across from Herald Square with café tables.',
    website: 'https://www.nycgovparks.org/parks/greeley-square',
    tags: ['Park', 'Seating'],
    hours: '24/7',
    address: 'W 32nd St & Broadway, New York, NY 10001',
    phone: '+1 212-768-3838',
  },
  'Manhattan Mall': {
    blurb: 'Vertical mall at 33rd & 6th above the subway.',
    website: 'https://www.manhattanmallny.com',
    tags: ['Shopping', 'Food court'],
    hours: 'Mon–Sat 10am–9pm, Sun 11am–8pm',
    address: '100 W 33rd St, New York, NY 10001',
    phone: '+1 212-465-0500',
  },
  'The Pennsy Food Hall': {
    blurb: 'Upscale food hall atop Penn Station.',
    website: 'https://www.thepennsyny.com',
    tags: ['Food hall', 'Takeout'],
    hours: 'Mon–Fri 7am–10pm, Sat–Sun 8am–10pm',
    address: '2 Penn Plaza, New York, NY 10121',
    phone: '+1 212-239-6200',
  },
  'Ace Hotel Lobby': {
    blurb: 'Buzzy lobby-as-living-room with coffee and cocktails.',
    website: 'https://acehotel.com/new-york',
    tags: ['Cocktails', 'Coffee', 'Wi-Fi'],
    hours: '24/7',
    address: '20 W 29th St, New York, NY 10001',
    phone: '+1 212-679-2222',
  },
  'Grand Central Terminal': {
    blurb: 'Beaux-Arts rail cathedral with the celestial ceiling.',
    website: 'https://www.grandcentralterminal.com',
    tags: ['Transit', 'Landmark', 'Dining'],
    hours: 'Daily 5:30am–2am',
    address: '89 E 42nd St, New York, NY 10017',
    phone: '+1 212-340-2583',
    rating: 4.8,
    ratingCount: 72004,
  },
  'Rockefeller Center': {
    blurb: 'Plaza, Top of the Rock, and the seasonal skating rink.',
    website: 'https://www.rockefellercenter.com',
    tags: ['Landmark', 'Observation', 'Shops'],
    hours: 'Daily 8am–12am',
    address: '45 Rockefeller Plaza, New York, NY 10111',
    phone: '+1 212-332-6868',
    rating: 4.7,
    ratingCount: 84221,
  },
  'St. Patrick’s Cathedral': {
    blurb: 'Neo-Gothic Catholic cathedral on Fifth Avenue.',
    website: 'https://saintpatrickscathedral.org',
    tags: ['Landmark', 'Free', 'Historic'],
    hours: 'Daily 6:30am–8:45pm',
    address: '5th Ave, New York, NY 10022',
    phone: '+1 212-753-2261',
  },
  'Union Square': {
    blurb: 'Greenmarket, statues and the city\'s favorite meeting steps.',
    website: 'https://www.nycgovparks.org/parks/union-square-park',
    tags: ['Park', 'Greenmarket', 'Transit'],
    hours: '24/7',
    address: '201 Park Ave S, New York, NY 10003',
    phone: '+1 212-460-1200',
    rating: 4.6,
    ratingCount: 21002,
  },
  'Chelsea Market': {
    blurb: 'Former Nabisco factory turned food hall and shops.',
    website: 'https://www.chelseamarket.com',
    tags: ['Food hall', 'Shopping'],
    hours: 'Mon–Sat 7am–9pm, Sun 8am–8pm',
    address: '75 9th Ave, New York, NY 10011',
    phone: '+1 212-652-2110',
    rating: 4.6,
    ratingCount: 68110,
  },
  'Hudson Yards (Vessel)': {
    blurb: 'Shops, restaurants and the honeycomb Vessel sculpture.',
    website: 'https://www.hudsonyardsnewyork.com',
    tags: ['Shopping', 'Landmark', 'Dining'],
    hours: 'Daily 10am–9pm',
    address: '20 Hudson Yards, New York, NY 10001',
    phone: '+1 332-204-8500',
  },
  'The High Line (W 14th)': {
    blurb: 'Elevated rail-to-park promenade over the West Side.',
    website: 'https://www.thehighline.org',
    tags: ['Park', 'Free', 'Walk'],
    hours: 'Daily 7am–10pm',
    address: 'W 14th St & Washington St, New York, NY 10014',
    phone: '+1 212-500-6035',
  },
  'Korilla / K-Town BBQ Row': {
    blurb: 'Korean BBQ and quick Korean eats along 32nd Street.',
    website: 'https://www.korillabbq.com',
    tags: ['Korean', 'BBQ'],
    hours: 'Daily 11am–2am',
    address: '32nd St between 5th & Broadway, New York, NY 10001',
    phone: '+1 646-429-6385',
  },
  'Jongro BBQ': {
    blurb: 'K-Town favorite for charcoal-grilled Korean BBQ.',
    website: 'https://www.jongrobbq.com',
    tags: ['Restaurant', 'Korean BBQ'],
    hours: 'Daily 11:30am–11pm',
    address: '22 W 32nd St, 2nd Fl, New York, NY 10001',
    rating: 4.5,
    ratingCount: 4200,
  },
  'Kang Ho Dong Baekjeong': {
    blurb: 'Buzzy tabletop Korean BBQ from a wrestling legend.',
    website: 'https://www.baekjeongnyc.com',
    tags: ['Restaurant', 'Korean BBQ'],
    hours: 'Daily 11:30am–12am',
    address: '1 E 32nd St, New York, NY 10016',
    phone: '+1 212-966-9839',
    rating: 4.5,
    ratingCount: 6100,
  },
  'BCD Tofu House': {
    blurb: 'Bubbling soondubu (soft tofu stew) day and night.',
    website: 'https://www.bcdtofuhouse.com',
    tags: ['Restaurant', 'Korean', 'Soft Tofu'],
    hours: 'Daily 10:30am–1am',
    address: '5 W 32nd St, New York, NY 10001',
    phone: '+1 212-967-1900',
    rating: 4.4,
    ratingCount: 5300,
  },
  'Cho Dang Gol': {
    blurb: 'Handmade tofu and homestyle Korean classics.',
    website: 'https://www.chodanggolnyc.com',
    tags: ['Restaurant', 'Korean', 'Tofu'],
    hours: 'Mon–Sun 12pm–2:30pm, 5pm–9:30pm',
    address: '55 W 35th St, New York, NY 10001',
  },
  'Her Name Is Han': {
    blurb: 'Modern Korean comfort food in a cozy room.',
    website: 'https://www.hernameishan.com',
    tags: ['Restaurant', 'Korean', 'Modern'],
    hours: 'Mon–Fri 11:30am–3pm & 5–10:30pm; Sat–Sun 11:30am–10:30pm',
    address: '17 E 31st St, New York, NY 10016',
    rating: 4.6,
    ratingCount: 3100,
  },
  'miss KOREA BBQ': {
    blurb: 'Three floors of Korean BBQ, open around the clock.',
    website: 'https://www.misskoreabbq.com',
    tags: ['Restaurant', 'Korean BBQ', '24hr'],
    hours: 'Open 24 hours',
    address: '10 W 32nd St, New York, NY 10001',
    rating: 4.4,
    ratingCount: 4800,
  },
  'New Wonjo': {
    blurb: '24-hour charcoal Korean BBQ stalwart.',
    tags: ['Restaurant', 'Korean BBQ'],
    hours: 'Open 24 hours',
    address: '23 W 32nd St, New York, NY 10001',
  },
  'Gaonnuri': {
    blurb: 'Upscale Korean dining with sweeping skyline views.',
    website: 'https://www.gaonnuri.com',
    tags: ['Restaurant', 'Korean', 'Fine Dining'],
    hours: 'Mon–Sun 11:30am–3pm, 5–10pm',
    address: '1250 Broadway, 39th Fl, New York, NY 10001',
    rating: 4.5,
    ratingCount: 1900,
  },
  'Pocha 32': {
    blurb: 'Tented K-Town pojangmacha for soju and late-night bites.',
    tags: ['Bar', 'Korean', 'Pojangmacha'],
    hours: 'Daily 5pm–4am',
    address: '15 W 32nd St, 2nd Fl, New York, NY 10001',
    rating: 4.3,
    ratingCount: 2200,
  },
  'Woorijip': {
    blurb: 'Grab-and-go Korean banchan bar and quick meals.',
    website: 'https://www.woorijipnyc.com',
    tags: ['Restaurant', 'Korean', 'Casual'],
    hours: 'Daily 8am–11pm',
    address: '12 W 32nd St, New York, NY 10001',
    rating: 4.3,
    ratingCount: 3000,
  },
  'Mandoo Bar': {
    blurb: 'Handmade dumplings folded in the front window.',
    tags: ['Restaurant', 'Korean', 'Dumplings'],
    hours: 'Daily 11:30am–10pm',
    address: '2 W 32nd St, New York, NY 10001',
    rating: 4.4,
    ratingCount: 2600,
  },
  'Dons Bogam': {
    blurb: 'Korean BBQ and wine in a polished setting.',
    website: 'https://www.donsbogam.com',
    tags: ['Restaurant', 'Korean BBQ', 'Wine'],
    hours: 'Daily 11:30am–11pm',
    address: '17 E 32nd St, New York, NY 10016',
  },
  'Hangawi': {
    blurb: 'Serene shoes-off temple of Korean vegetarian cuisine.',
    website: 'https://www.hangawirestaurant.com',
    tags: ['Restaurant', 'Korean', 'Vegetarian'],
    hours: 'Mon–Sun 12pm–3pm, 5–10pm',
    address: '12 E 32nd St, New York, NY 10016',
    phone: '+1 212-213-0077',
    rating: 4.6,
    ratingCount: 2400,
  },
  'Kunjip': {
    blurb: 'All-day Korean comfort classics in the heart of K-Town.',
    website: 'https://www.kunjip.net',
    tags: ['Restaurant', 'Korean', 'Casual'],
    hours: 'Daily 11am–12am',
    address: '9 W 32nd St, New York, NY 10001',
    rating: 4.3,
    ratingCount: 4100,
  },
  'Hojokban': {
    blurb: 'Modern Korean comfort food and soju upstairs.',
    website: 'https://hojokban.com/new-york/home',
    tags: ['Restaurant', 'Korean', 'Comfort Food'],
    hours: 'Daily 11:30am–11pm',
    address: '7 W 32nd St, 3rd Fl, New York, NY 10001',
  },
  'Soju Haus': {
    blurb: 'Soju, anju and K-pop energy above Fifth Avenue.',
    tags: ['Bar', 'Korean', 'Soju'],
    hours: 'Daily 4pm–2am',
    address: '315 5th Ave, 2nd Fl, New York, NY 10016',
  },
  'Joo Ok': {
    blurb: 'Refined Korean tasting menu high above K-Town.',
    website: 'https://www.joo-ok.com',
    tags: ['Restaurant', 'Korean', 'Tasting Menu'],
    hours: 'Tue–Sat seatings 5:30pm–9pm (by reservation)',
    address: '22 W 32nd St, 16th Fl, New York, NY 10001',
    rating: 4.6,
    ratingCount: 420,
  },
  'Turntable Chicken Jazz': {
    blurb: 'Korean fried chicken and beer with a vinyl-jazz soundtrack.',
    website: 'https://turntablenyc.com',
    tags: ['Korean Fried Chicken', 'Bar'],
    hours: 'Daily 11:30am–12am',
    address: '20 W 33rd St, New York, NY 10001',
    rating: 4.3,
    ratingCount: 1500,
  },
  'Little Ned': {
    blurb: 'Plush NoMad cocktail lounge for a low-lit night.',
    tags: ['Bar', 'Cocktails', 'Lounge'],
    hours: 'Daily 4pm–2am',
    address: '7 E 27th St, New York, NY 10016',
    rating: 4.4,
    ratingCount: 300,
  },
  'Patent Pending': {
    blurb: 'Speakeasy behind a coffee shop in Tesla\'s old workshop.',
    website: 'https://www.patentpendingnyc.com',
    tags: ['Bar', 'Cocktails', 'Speakeasy'],
    hours: 'Tue–Sat 5pm–12am',
    address: '49 W 27th St, New York, NY 10001',
    rating: 4.6,
    ratingCount: 1200,
  },
  'The Ivory Peacock': {
    blurb: 'Art-nouveau cocktail parlor heavy on the gin.',
    tags: ['Bar', 'Cocktails', 'Gin'],
    hours: 'Mon–Sat 5pm–12am',
    address: '45 W 29th St, New York, NY 10001',
    rating: 4.5,
    ratingCount: 260,
  },
  'Nubeluz by Jose Andres': {
    blurb: 'José Andrés\' sky-high rooftop cocktail salon.',
    website: 'https://www.nubeluznyc.com',
    tags: ['Bar', 'Cocktails', 'Rooftop'],
    hours: 'Wed–Sun 5pm–1am',
    address: '25 W 28th St, 50th Fl, New York, NY 10001',
    rating: 4.4,
    ratingCount: 900,
  },
  'Brass': {
    blurb: 'Buzzy NoMad seafood brasserie and raw bar.',
    tags: ['Restaurant', 'Bar', 'Seafood'],
    hours: 'Daily 4pm–12am',
    address: '1185 Broadway, New York, NY 10001',
    rating: 4.4,
    ratingCount: 800,
  },
  'Koloman': {
    blurb: 'Elegant Austrian-French dining off Fifth Avenue.',
    website: 'https://www.kolomanrestaurant.com',
    tags: ['Restaurant', 'Bar', 'Austrian/French'],
    hours: 'Daily 5pm–11pm',
    address: '16 W 29th St, New York, NY 10001',
    rating: 4.5,
    ratingCount: 650,
  },
  'Oscar Wilde': {
    blurb: 'Opulent 100-ft bar dripping in Victorian decor.',
    website: 'https://www.oscarwildenyc.com',
    tags: ['Bar', 'Cocktails', 'Historic'],
    hours: 'Daily 11:30am–2am',
    address: '45 W 27th St, New York, NY 10001',
    rating: 4.5,
    ratingCount: 4300,
  },
  'Swingers NoMad': {
    blurb: 'Crazy-golf bar with cocktails and street food.',
    website: 'https://swingers.club',
    tags: ['Bar', 'Mini Golf', 'Cocktails'],
    hours: 'Mon–Sun 12pm–12am (21+ evenings)',
    address: '35 W 29th St, New York, NY 10001',
    rating: 4.4,
    ratingCount: 1100,
  },
  'The Portrait Bar': {
    blurb: 'Jewel-box hotel bar at The Fifth Avenue Hotel.',
    website: 'https://www.thefifthavenuehotel.com',
    tags: ['Bar', 'Cocktails', 'Hotel'],
    hours: 'Daily 4pm–1am',
    address: '250 5th Ave, New York, NY 10001',
    rating: 4.5,
    ratingCount: 420,
  },
  'K32 Rooftop Bar': {
    blurb: 'Open-air rooftop over K-Town for soju cocktails.',
    tags: ['Bar', 'Rooftop', 'Korean'],
    hours: 'Daily 5pm–2am',
    address: '22 W 32nd St, Rooftop, New York, NY 10001',
  },
  'Mustang Harry\'s': {
    blurb: 'Cavernous Irish sports bar near the Garden.',
    website: 'https://www.mustangharrys.com',
    tags: ['Bar', 'Sports Bar', 'Irish Pub'],
    hours: 'Daily 11am–2am',
    address: '352 7th Ave, New York, NY 10001',
    phone: '+1 212-268-8930',
    rating: 4.3,
    ratingCount: 1700,
  },
  'The Liberty NYC': {
    blurb: 'Neighborhood cocktail bar near Herald Square.',
    website: 'https://www.thelibertynyc.com',
    tags: ['Bar', 'Cocktails'],
    hours: 'Daily 4pm–2am',
    address: '29 W 35th St, New York, NY 10001',
    rating: 4.4,
    ratingCount: 500,
  },
  'The Ragtrader': {
    blurb: 'Garment-district restaurant and bar in a former school.',
    website: 'https://www.theragtrader.com',
    tags: ['Restaurant', 'Bar', 'American'],
    hours: 'Daily 7am–11pm',
    address: '70 W 36th St, New York, NY 10018',
    rating: 4.3,
    ratingCount: 700,
  },
  'Stout NYC': {
    blurb: 'Huge Irish gastropub steps from the Garden.',
    website: 'https://www.stoutnyc.com',
    tags: ['Bar', 'Irish Pub', 'Gastropub'],
    hours: 'Daily 11am–4am',
    address: '133 W 33rd St, New York, NY 10001',
    rating: 4.2,
    ratingCount: 1400,
  },
  'Grace Street Coffee & Desserts': {
    blurb: 'K-Town café for honey toast, bingsu and lattes.',
    tags: ['Dessert', 'Café', 'Bingsu'],
    hours: 'Daily 12pm–12am',
    address: '17 W 32nd St, New York, NY 10001',
    rating: 4.5,
    ratingCount: 2600,
  },
  'Angelina Bakery Herald Square': {
    blurb: 'Italian bakery famous for cronut-style pastries.',
    website: 'https://angelinabakery.com',
    tags: ['Dessert', 'Bakery', 'Italian'],
    hours: 'Daily 7am–10pm',
    address: '1283 Broadway, New York, NY 10001',
    rating: 4.4,
    ratingCount: 1500,
  },
  'Tous Les Jours': {
    blurb: 'Korean-French bakery-café with cakes and buns.',
    website: 'https://www.tlj.com',
    tags: ['Dessert', 'Bakery', 'Korean-French'],
    hours: 'Daily 7am–10pm',
    address: '4 W 32nd St, New York, NY 10001',
    rating: 4.3,
    ratingCount: 1100,
  },
  'Paris Baguette': {
    blurb: 'Pastries, cakes and coffee in the heart of K-Town.',
    website: 'https://www.parisbaguette.com',
    tags: ['Dessert', 'Bakery', 'Café'],
    hours: 'Daily 7am–10pm',
    address: '6 W 32nd St, New York, NY 10001',
    rating: 4.3,
    ratingCount: 1300,
  },
  'Zaro\'s Family Bakery (Macy\'s)': {
    blurb: 'NYC family bakery counter inside Macy\'s.',
    website: 'https://www.zaro.com',
    tags: ['Dessert', 'Bakery'],
    hours: 'Mon–Fri 10am–9pm, Sat–Sun 10am–8pm',
    address: '151 W 34th St, 6th Fl, New York, NY 10001',
  },
  'Carvel (Macy\'s Herald Square)': {
    blurb: 'Soft-serve and ice-cream cakes inside Macy\'s.',
    website: 'https://www.carvel.com',
    tags: ['Dessert', 'Ice Cream'],
    hours: 'Mon–Sat 10am–9pm, Sun 11am–8pm',
    address: '151 W 34th St, 7th Fl, New York, NY 10001',
  },
  'NY Bakery and Desserts': {
    blurb: 'Cozy NoMad spot for cakes, coffee and pastries.',
    tags: ['Dessert', 'Bakery', 'Café'],
    hours: 'Daily 8am–10pm',
    address: '1204 Broadway, New York, NY 10001',
  },
  'Maman': {
    blurb: 'French-inspired café known for the nutty chocolate cookie.',
    website: 'https://www.mamannyc.com',
    tags: ['Dessert', 'Bakery', 'Café'],
    hours: 'Daily 7am–7pm',
    address: '162 5th Ave, New York, NY 10010',
    rating: 4.5,
    ratingCount: 2100,
  },
  'Keens Steakhouse': {
    blurb: '1885 chophouse famous for mutton chops and pipes.',
    website: 'https://www.keens.com',
    tags: ['Steakhouse', 'Historic'],
    hours: 'Mon–Fri 11:45am–10:30pm, Sat–Sun 5pm–10:30pm',
    address: '72 W 36th St, New York, NY 10018',
    phone: '+1 212-947-3636',
    rating: 4.7,
    ratingCount: 5200,
  },
  'Stella 34 Trattoria': {
    blurb: 'Italian trattoria with Empire State views inside Macy\'s.',
    website: 'https://www.stella34.com',
    tags: ['Italian'],
    hours: 'Daily 11:30am–9pm',
    address: '151 W 34th St, 6th Fl (Macy\'s), New York, NY 10001',
    rating: 4.4,
    ratingCount: 3200,
  },
  'The Smith NoMad': {
    blurb: 'Bustling all-day American brasserie.',
    website: 'https://www.thesmithrestaurant.com',
    tags: ['American', 'Brasserie'],
    hours: 'Daily 8am–11pm',
    address: '1150 Broadway, New York, NY 10001',
    rating: 4.5,
    ratingCount: 4600,
  },
  'Friedman\'s Herald Square': {
    blurb: 'Comfort-food American spot with big GF menu.',
    website: 'https://www.friedmansrestaurant.com',
    tags: ['American', 'Gluten-Free'],
    hours: 'Daily 9am–10pm',
    address: '138 W 31st St, New York, NY 10001',
    rating: 4.4,
    ratingCount: 2300,
  },
  'Ai Fiori': {
    blurb: 'Michelin-starred Italian-Riviera fine dining.',
    website: 'https://www.aifiorinyc.com',
    tags: ['Italian', 'Fine Dining'],
    hours: 'Mon–Sat 12pm–2:30pm, 5–10pm',
    address: '400 5th Ave, 2nd Fl, New York, NY 10018',
    rating: 4.6,
    ratingCount: 1900,
  },
  'Wolfgang\'s Steakhouse (Park Ave)': {
    blurb: 'Dry-aged porterhouse in a landmarked Park Ave room.',
    website: 'https://www.wolfgangssteakhouse.net',
    tags: ['Steakhouse'],
    hours: 'Daily 12pm–10:30pm',
    address: '4 Park Ave, New York, NY 10016',
    rating: 4.5,
    ratingCount: 2700,
  },
  'Hill Country Barbecue Market': {
    blurb: 'Central-Texas BBQ by the pound with live music.',
    website: 'https://www.hillcountry.com',
    tags: ['BBQ', 'Texan'],
    hours: 'Daily 11:30am–10pm',
    address: '30 W 26th St, New York, NY 10010',
    rating: 4.4,
    ratingCount: 3100,
  },
  'Marta': {
    blurb: 'Wood-fired Roman-style thin-crust pizza.',
    website: 'https://www.martamanhattan.com',
    tags: ['Italian', 'Roman Pizza'],
    hours: 'Daily 11:30am–11pm',
    address: '29 E 29th St, New York, NY 10016',
    rating: 4.5,
    ratingCount: 2500,
  },
  'Scarpetta': {
    blurb: 'Polished Italian known for its silky spaghetti.',
    website: 'https://www.scarpettarestaurants.com',
    tags: ['Italian', 'Fine Dining'],
    hours: 'Daily 5pm–10:30pm',
    address: '88 Madison Ave, New York, NY 10016',
    rating: 4.5,
    ratingCount: 2900,
  },
  'La Pecora Bianca NoMad': {
    blurb: 'Sunny market-driven Italian in NoMad.',
    website: 'https://www.lapecorabianca.com',
    tags: ['Italian'],
    hours: 'Daily 8am–10pm',
    address: '1133 Broadway, New York, NY 10010',
    rating: 4.4,
    ratingCount: 1800,
  },
  'Zaytinya by Jose Andres': {
    blurb: 'José Andrés\' Greek-Turkish-Lebanese mezze.',
    website: 'https://www.zaytinya.com',
    tags: ['Mediterranean', 'Mezze'],
    hours: 'Daily 11:30am–10pm',
    address: '1185 Broadway, New York, NY 10001',
    rating: 4.5,
    ratingCount: 1600,
  },
  'The Clocktower': {
    blurb: 'Michelin-starred British dining in the clocktower.',
    website: 'https://www.theclocktowernyc.com',
    tags: ['British', 'Fine Dining'],
    hours: 'Daily 7am–10:30pm',
    address: '5 Madison Ave, 2nd Fl, New York, NY 10010',
    rating: 4.5,
    ratingCount: 2000,
  },
  'Eleven Madison Park': {
    blurb: 'World-renowned plant-based tasting menu.',
    website: 'https://www.elevenmadisonpark.com',
    tags: ['Fine Dining', 'Tasting Menu'],
    hours: 'Wed–Sun seatings (by reservation)',
    address: '11 Madison Ave, New York, NY 10010',
    phone: '+1 212-889-0905',
    rating: 4.6,
    ratingCount: 5400,
  },
};

export function placeInfoFor(name: string): PlaceInfo {
  return PLACE_INFO[name] ?? {};
}

export function mapsSearchUrl(name: string): string {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(name + ', New York, NY')}`;
}
export function mapsDirectionsUrl(lat: number, lng: number): string {
  return `https://www.google.com/maps/dir/?api=1&destination=${lat},${lng}`;
}
